# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import data_plane_pb2 as simba_dot_v1_dot_data__plane__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in simba/v1/data_plane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """data_plane.proto — worker <-> engine.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Claim = channel.stream_stream(
                '/simba.v1.WorkerService/Claim',
                request_serializer=simba_dot_v1_dot_data__plane__pb2.ClaimRequest.SerializeToString,
                response_deserializer=simba_dot_v1_dot_data__plane__pb2.JobAssignment.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/simba.v1.WorkerService/Heartbeat',
                request_serializer=simba_dot_v1_dot_data__plane__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=simba_dot_v1_dot_data__plane__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Complete = channel.unary_unary(
                '/simba.v1.WorkerService/Complete',
                request_serializer=simba_dot_v1_dot_data__plane__pb2.CompleteRequest.SerializeToString,
                response_deserializer=simba_dot_v1_dot_data__plane__pb2.CompleteResponse.FromString,
                _registered_method=True)
        self.Fail = channel.unary_unary(
                '/simba.v1.WorkerService/Fail',
                request_serializer=simba_dot_v1_dot_data__plane__pb2.FailRequest.SerializeToString,
                response_deserializer=simba_dot_v1_dot_data__plane__pb2.FailResponse.FromString,
                _registered_method=True)
        self.Wait = channel.unary_unary(
                '/simba.v1.WorkerService/Wait',
                request_serializer=simba_dot_v1_dot_data__plane__pb2.WaitRequest.SerializeToString,
                response_deserializer=simba_dot_v1_dot_data__plane__pb2.WaitResponse.FromString,
                _registered_method=True)
        self.PutCheckpoint = channel.unary_unary(
                '/simba.v1.WorkerService/PutCheckpoint',
                request_serializer=simba_dot_v1_dot_data__plane__pb2.PutCheckpointRequest.SerializeToString,
                response_deserializer=simba_dot_v1_dot_data__plane__pb2.PutCheckpointResponse.FromString,
                _registered_method=True)
        self.GetCheckpoint = channel.unary_unary(
                '/simba.v1.WorkerService/GetCheckpoint',
                request_serializer=simba_dot_v1_dot_data__plane__pb2.GetCheckpointRequest.SerializeToString,
                response_deserializer=simba_dot_v1_dot_data__plane__pb2.GetCheckpointResponse.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/simba.v1.WorkerService/GetResult',
                request_serializer=simba_dot_v1_dot_data__plane__pb2.GetResultRequest.SerializeToString,
                response_deserializer=simba_dot_v1_dot_data__plane__pb2.GetResultResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """data_plane.proto — worker <-> engine.

    """

    def Claim(self, request_iterator, context):
        """Bidirectional stream, one per worker process. Worker announces itself and
        keeps free_slots current; engine pushes assignments. Flow control is
        worker-driven: the engine never assigns beyond the last announced slots.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """unary, cheap
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Wait(self, request, context):
        """park the job until a signal arrives
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutCheckpoint(self, request, context):
        """persist resumable progress
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Lazy tier: fetch a deep ancestor's result on demand. Reads jobs_all
        (hot first, archive fallback), scoped to the caller's ctx_id + tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Claim': grpc.stream_stream_rpc_method_handler(
                    servicer.Claim,
                    request_deserializer=simba_dot_v1_dot_data__plane__pb2.ClaimRequest.FromString,
                    response_serializer=simba_dot_v1_dot_data__plane__pb2.JobAssignment.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=simba_dot_v1_dot_data__plane__pb2.HeartbeatRequest.FromString,
                    response_serializer=simba_dot_v1_dot_data__plane__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=simba_dot_v1_dot_data__plane__pb2.CompleteRequest.FromString,
                    response_serializer=simba_dot_v1_dot_data__plane__pb2.CompleteResponse.SerializeToString,
            ),
            'Fail': grpc.unary_unary_rpc_method_handler(
                    servicer.Fail,
                    request_deserializer=simba_dot_v1_dot_data__plane__pb2.FailRequest.FromString,
                    response_serializer=simba_dot_v1_dot_data__plane__pb2.FailResponse.SerializeToString,
            ),
            'Wait': grpc.unary_unary_rpc_method_handler(
                    servicer.Wait,
                    request_deserializer=simba_dot_v1_dot_data__plane__pb2.WaitRequest.FromString,
                    response_serializer=simba_dot_v1_dot_data__plane__pb2.WaitResponse.SerializeToString,
            ),
            'PutCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.PutCheckpoint,
                    request_deserializer=simba_dot_v1_dot_data__plane__pb2.PutCheckpointRequest.FromString,
                    response_serializer=simba_dot_v1_dot_data__plane__pb2.PutCheckpointResponse.SerializeToString,
            ),
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=simba_dot_v1_dot_data__plane__pb2.GetCheckpointRequest.FromString,
                    response_serializer=simba_dot_v1_dot_data__plane__pb2.GetCheckpointResponse.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=simba_dot_v1_dot_data__plane__pb2.GetResultRequest.FromString,
                    response_serializer=simba_dot_v1_dot_data__plane__pb2.GetResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simba.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simba.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """data_plane.proto — worker <-> engine.

    """

    @staticmethod
    def Claim(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/simba.v1.WorkerService/Claim',
            simba_dot_v1_dot_data__plane__pb2.ClaimRequest.SerializeToString,
            simba_dot_v1_dot_data__plane__pb2.JobAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simba.v1.WorkerService/Heartbeat',
            simba_dot_v1_dot_data__plane__pb2.HeartbeatRequest.SerializeToString,
            simba_dot_v1_dot_data__plane__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simba.v1.WorkerService/Complete',
            simba_dot_v1_dot_data__plane__pb2.CompleteRequest.SerializeToString,
            simba_dot_v1_dot_data__plane__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simba.v1.WorkerService/Fail',
            simba_dot_v1_dot_data__plane__pb2.FailRequest.SerializeToString,
            simba_dot_v1_dot_data__plane__pb2.FailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Wait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simba.v1.WorkerService/Wait',
            simba_dot_v1_dot_data__plane__pb2.WaitRequest.SerializeToString,
            simba_dot_v1_dot_data__plane__pb2.WaitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simba.v1.WorkerService/PutCheckpoint',
            simba_dot_v1_dot_data__plane__pb2.PutCheckpointRequest.SerializeToString,
            simba_dot_v1_dot_data__plane__pb2.PutCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simba.v1.WorkerService/GetCheckpoint',
            simba_dot_v1_dot_data__plane__pb2.GetCheckpointRequest.SerializeToString,
            simba_dot_v1_dot_data__plane__pb2.GetCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simba.v1.WorkerService/GetResult',
            simba_dot_v1_dot_data__plane__pb2.GetResultRequest.SerializeToString,
            simba_dot_v1_dot_data__plane__pb2.GetResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
